In [2]:
pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl
Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.0.1 -> 25.1.1
[notice] To update, run: C:\Users\USER\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip

## Objective

possibilities of having cancer based on their lifestyles

Due to the lifestyle they choose
    Alcohol use,,Obesity,Smoking
Due to a good Lifestyle
    Balanced Diet
Due to living condition
    Air pollution,Dust Allergy,Occupational hazard,passive smoking
Due to Heriditary
    Genetic Risk
Symptoms of a person have Cancer
    Chronic Lung Disease,Chest Pain,Coughing of blood,Fatigue,Weight Loss,Shortness of Breath,Wheezing,Swallowing Difficulty,Clubbing of finger Nails,frequent cold,Dry Cough

    How much these symptoms are related to their cancer level
    
    why the people choose to be higly chose bad lifestyle by analyzing the living condition we can figure that out

    what are the factors that made the prople who had a very healthy diest subjected to cancer
    
    at last how snoring affects the cancer experimental

In [1]:
import pandas as pd
import openpyxl

In [118]:
df = pd.read_excel("./dataset/cancer.xlsx")
df.head()
reasons = ["Patient Id","Age","Gender","Air Pollution","Alcohol use","OccuPational Hazards","Genetic Risk","Balanced Diet","Obesity","Smoking","Passive Smoker","Level"]
symptoms = ["Dust Allergy","Chronic Lung Disease","Chest Pain","Coughing of Blood","Fatigue","Weight Loss","Shortness of breath","Wheezing","Swallowing Difficulty","Clubbing of Finger Nails","Frequent Cold","Dry Cough"]

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 25 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Patient Id                1000 non-null   object
 1   Age                       1000 non-null   int64
 2   Gender                    1000 non-null   int64
 3   Air Pollution             1000 non-null   int64
 4   Alcohol use               1000 non-null   int64
 5   Dust Allergy              1000 non-null   int64
 6   OccuPational Hazards      1000 non-null   int64
 7   Genetic Risk              1000 non-null   int64
 8   chronic Lung Disease      1000 non-null   int64
 9   Balanced Diet             1000 non-null   int64
 10  Obesity                   1000 non-null   int64
 11  Smoking                   1000 non-null   int64
 12  Passive Smoker            1000 non-null   int64
 13  Chest Pain                1000 non-null   int64
 14  Coughing of Blood         1000 non-null   int64
 15  Fatigue                   1000 non-null   int64
 16  Weight Loss               1000 non-null   int64
 17  Shortness of Breath       1000 non-null   int64
 18  Wheezing                  1000 non-null   int64
 19  Swallowing Difficulty     1000 non-null   int64
 20  Clubbing of Finger Nails  1000 non-null   int64
 21  Frequent Cold             1000 non-null   int64
 22  Dry Cough                 1000 non-null   int64
 23  Snoring                   1000 non-null   int64
 24  Level                     1000 non-null   object
dtypes: int64(23), object(2)
memory usage: 195.4+ KB

In [15]:
print(df.describe())

               Age       Gender  Air Pollution  Alcohol use  Dust Allergy  \
count  1000.000000  1000.000000      1000.0000  1000.000000   1000.000000
mean     37.174000     1.402000         3.8400     4.563000      5.165000
std      12.005493     0.490547         2.0304     2.620477      1.980833
min      14.000000     1.000000         1.0000     1.000000      1.000000
25%      27.750000     1.000000         2.0000     2.000000      4.000000
50%      36.000000     1.000000         3.0000     5.000000      6.000000
75%      45.000000     2.000000         6.0000     7.000000      7.000000
max      73.000000     2.000000         8.0000     8.000000      8.000000

       OccuPational Hazards  Genetic Risk  chronic Lung Disease  \
count           1000.000000   1000.000000           1000.000000
mean               4.840000      4.580000              4.380000
std                2.107805      2.126999              1.848518
min                1.000000      1.000000              1.000000
25%                3.000000      2.000000              3.000000
50%                5.000000      5.000000              4.000000
75%                7.000000      7.000000              6.000000
max                8.000000      7.000000              7.000000

       Balanced Diet      Obesity  ...  Coughing of Blood      Fatigue  \
count    1000.000000  1000.000000  ...        1000.000000  1000.000000
mean        4.491000     4.465000  ...           4.859000     3.856000
std         2.135528     2.124921  ...           2.427965     2.244616
min         1.000000     1.000000  ...           1.000000     1.000000
25%         2.000000     3.000000  ...           3.000000     2.000000
50%         4.000000     4.000000  ...           4.000000     3.000000
75%         7.000000     7.000000  ...           7.000000     5.000000
max         7.000000     7.000000  ...           9.000000     9.000000

       Weight Loss  Shortness of Breath     Wheezing  Swallowing Difficulty  \
count  1000.000000          1000.000000  1000.000000            1000.000000
mean      3.855000             4.240000     3.777000               3.746000
std       2.206546             2.285087     2.041921               2.270383
min       1.000000             1.000000     1.000000               1.000000
25%       2.000000             2.000000     2.000000               2.000000
50%       3.000000             4.000000     4.000000               4.000000
75%       6.000000             6.000000     5.000000               5.000000
max       8.000000             9.000000     8.000000               8.000000

       Clubbing of Finger Nails  Frequent Cold    Dry Cough      Snoring
count               1000.000000    1000.000000  1000.000000  1000.000000
mean                   3.923000       3.536000     3.853000     2.926000
std                    2.388048       1.832502     2.039007     1.474686
min                    1.000000       1.000000     1.000000     1.000000
25%                    2.000000       2.000000     2.000000     2.000000
50%                    4.000000       3.000000     4.000000     3.000000
75%                    5.000000       5.000000     6.000000     4.000000
max                    9.000000       7.000000     7.000000     7.000000

[8 rows x 23 columns]

In [6]:
df.duplicated().sum()
#0 duplicate value

np.int64(0)

In [17]:
bad_lifestyle = df.loc[(df["Smoking"]>5) & (df["Alcohol use"]>5) & (df["Air Pollution"]<5) & (df["OccuPational Hazards"] <5) & (df["Balanced Diet"]<5) & (df["Passive Smoker"]<5)]
bad_lifestyle
## according to the data given there are no person who got cancer due to drinking and smoking only

Empty DataFrame
Columns: [Patient Id, Age, Gender, Air Pollution, Alcohol use, Dust Allergy, OccuPational Hazards, Genetic Risk, chronic Lung Disease, Balanced Diet, Obesity, Smoking, Passive Smoker, Chest Pain, Coughing of Blood, Fatigue, Weight Loss, Shortness of Breath, Wheezing, Swallowing Difficulty, Clubbing of Finger Nails, Frequent Cold, Dry Cough, Snoring, Level]
Index: []

[0 rows x 25 columns]

In [20]:
uh= df.loc[(df["Smoking"]>5) & (df["Alcohol use"]>5),["Patient Id","Age","Gender","Air Pollution","Alcohol use","OccuPational Hazards","Genetic Risk","Balanced Diet","Obesity","Smoking","Passive Smoker","Level"]]
uh.loc[uh["Age"] < 20]

,Patient Id,Age,Gender,Air Pollution,Alcohol use,OccuPational Hazards,Genetic Risk,Balanced Diet,Obesity,Smoking,Passive Smoker,Level
98,P187,19,1,6,8,7,7,7,7,7,8,High
110,P198,18,2,6,8,7,7,7,7,8,7,High
209,P287,19,1,6,8,7,7,7,7,7,8,High
221,P298,18,2,6,8,7,7,7,7,8,7,High
320,P387,19,1,6,8,7,7,7,7,7,8,High
332,P398,18,2,6,8,7,7,7,7,8,7,High
431,P487,19,1,6,8,7,7,7,7,7,8,High
542,P587,19,1,6,8,7,7,7,7,7,8,High
554,P598,18,2,6,8,7,7,7,7,8,7,High
653,P687,19,1,6,8,7,7,7,7,7,8,High
665,P698,18,2,6,8,7,7,7,7,8,7,High
764,P787,19,1,6,8,7,7,7,7,7,8,High
776,P798,18,2,6,8,7,7,7,7,8,7,High
834,P85,19,1,6,8,7,7,7,7,7,8,High
875,P887,19,1,6,8,7,7,7,7,7,8,High
887,P898,18,2,6,8,7,7,7,7,8,7,High
956,P96,18,2,6,8,7,7,7,7,8,7,High
986,P987,19,1,6,8,7,7,7,7,7,8,High
998,P998,18,2,6,8,7,7,7,7,8,7,High

* Here we get that the young womens who are addicted to both Alchohol, and Smoking had a high level cancer, While according to our data there are no person who got cancer due to the smoking and drinking only
* and their from this data we can derive that the atmosher they lived maore likey to have a high level cancer ,
* passive smoker data says that they were surrownded with the people smoking, and may got their habit from their friends, while the fact that they all have high level Genetic risk and obesity even after a great diet

In [16]:
unhealthy_mid = df.loc[(df["Smoking"]>5) & (df["Alcohol use"]>5),["Patient Id","Age","Gender","Air Pollution","Alcohol use","OccuPational Hazards","Genetic Risk","Balanced Diet","Obesity","Smoking","Passive Smoker","Level"]]
unhealthy_mid.loc[(unhealthy_mid["Age"] < 51) & (unhealthy_mid["Age"] >19) & ( (unhealthy_mid["Air Pollution"] == unhealthy_mid["Air Pollution"].min()) | (unhealthy_mid["Alcohol use"] == unhealthy_mid["Alcohol use"].min()) | (unhealthy_mid["OccuPational Hazards"] == unhealthy_mid["OccuPational Hazards"].min()) | (unhealthy_mid["Genetic Risk"] == unhealthy_mid["Genetic Risk"].min()) | (unhealthy_mid["Balanced Diet"] == unhealthy_mid["Balanced Diet"].min()) | (unhealthy_mid["Obesity"] == df["Obesity"].min()) | (unhealthy_mid["Smoking"] == df["Smoking"].min()) | (unhealthy_mid["Smoking"] == unhealthy_mid["Smoking"].min()))]

,Patient Id,Age,Gender,Air Pollution,Alcohol use,OccuPational Hazards,Genetic Risk,Balanced Diet,Obesity,Smoking,Passive Smoker,Level
3,P1000,37,1,7,7,7,6,7,7,7,7,High
13,P11,34,1,6,7,7,6,7,7,7,7,High
17,P113,34,1,6,7,7,6,7,7,7,7,High
18,P114,36,1,6,7,7,7,6,7,7,7,High
20,P116,24,1,6,8,7,6,7,3,8,7,High
...,...,...,...,...,...,...,...,...,...,...,...,...
912,P92,33,1,6,7,7,7,6,7,7,7,High
918,P925,35,2,2,6,3,6,6,4,6,8,High
989,P99,37,1,7,7,7,6,7,7,7,7,High
993,P993,37,2,7,7,7,6,7,7,7,7,High
994,P994,33,1,6,7,7,7,6,7,7,7,High

In [31]:
uh.loc[(unhealthy_mid["Alcohol use"] >7) & (uh["Smoking"] > 7) & (uh["Age"] >= 20) & (uh["Age"] <= 50)].describe()

#nearly 20% of the patients who were heavily addicted to smoking and alcohol got the cancer at highlevel and they lived in a higly unhealthy conditions with a great helthy diet of 7 while the occupational hazard and passive smoing shows they worked on harmul condtions but along with the people smoking which may lead to them beign a addicted to smoking and drinking

,Patient Id,Age,Gender,Air Pollution,Alcohol use,OccuPational Hazards,Genetic Risk,Balanced Diet,Obesity,Smoking,Passive Smoker,Level
4,P101,46,1,6,8,7,7,7,7,8,7,High
20,P116,24,1,6,8,7,6,7,3,8,7,High
46,P14,24,1,6,8,7,6,7,3,8,7,High
93,P182,46,2,6,8,7,7,7,7,8,7,High
100,P189,39,2,6,8,7,7,7,7,8,7,High
103,P191,37,1,8,8,7,7,7,7,8,7,High
114,P200,26,2,8,8,7,7,7,7,8,7,High
131,P216,24,1,6,8,7,6,7,3,8,7,High
204,P282,46,1,6,8,7,7,7,7,8,7,High
211,P289,39,2,6,8,7,7,7,7,8,7,High
214,P291,37,1,8,8,7,7,7,7,8,7,High
225,P300,26,2,8,8,7,7,7,7,8,7,High
242,P316,24,1,6,8,7,6,7,3,8,7,High
315,P382,46,1,6,8,7,7,7,7,8,7,High
322,P389,39,2,6,8,7,7,7,7,8,7,High
325,P391,37,1,8,8,7,7,7,7,8,7,High
336,P400,26,2,8,8,7,7,7,7,8,7,High
353,P416,24,1,6,8,7,6,7,3,8,7,High
426,P482,46,1,6,8,7,7,7,7,8,7,High
433,P489,39,1,6,8,7,7,7,7,8,7,High
436,P491,37,1,8,8,7,7,7,7,8,7,High
443,P498,28,1,6,8,7,7,7,7,8,7,High
447,P500,26,2,8,8,7,7,7,7,8,7,High
464,P516,24,1,6,8,7,6,7,3,8,7,High
537,P582,46,1,6,8,7,7,7,7,8,7,High
544,P589,39,2,6,8,7,7,7,7,8,7,High
547,P591,37,1,8,8,7,7,7,7,8,7,High
558,P600,26,2,8,8,7,7,7,7,8,7,High
575,P616,24,1,6,8,7,6,7,3,8,7,High
648,P682,46,1,6,8,7,7,7,7,8,7,High
655,P689,39,2,6,8,7,7,7,7,8,7,High
658,P691,37,1,8,8,7,7,7,7,8,7,High
669,P700,26,2,8,8,7,7,7,7,8,7,High
686,P716,24,1,6,8,7,6,7,3,8,7,High
759,P782,46,1,6,8,7,7,7,7,8,7,High
766,P789,39,2,6,8,7,7,7,7,8,7,High
769,P791,37,1,8,8,7,7,7,7,8,7,High
779,P80,46,1,6,8,7,7,7,7,8,7,High
780,P800,26,2,8,8,7,7,7,7,8,7,High
797,P816,24,1,6,8,7,6,7,3,8,7,High
856,P87,39,2,6,8,7,7,7,7,8,7,High
870,P882,46,1,6,8,7,7,7,7,8,7,High
877,P889,39,2,6,8,7,7,7,7,8,7,High
878,P89,37,1,8,8,7,7,7,7,8,7,High
880,P891,37,1,8,8,7,7,7,7,8,7,High
891,P900,26,2,8,8,7,7,7,7,8,7,High
908,P916,24,1,6,8,7,6,7,3,8,7,High
978,P98,26,2,8,8,7,7,7,7,8,7,High
981,P982,46,1,6,8,7,7,7,7,8,7,High
988,P989,39,2,6,8,7,7,7,7,8,7,High
991,P991,37,1,8,8,7,7,7,7,8,7,High

In [34]:

uh.loc[ (uh["Age"] >50) & (uh["Age"] <= 80) & (uh["Level"] == "Medium")]
#comparing to others the old people who got medium cancer

#lives in a compritively better enviornement
#low occupatinal hard
#low alcohol usage
#as a result they got medium level cancer , which shows how much important is the enviornement at this same level of evniroement condtion lets check how the rest of the patients does

,Patient Id,Age,Gender,Air Pollution,Alcohol use,OccuPational Hazards,Genetic Risk,Balanced Diet,Obesity,Smoking,Passive Smoker,Level
15,P111,73,1,5,6,5,6,6,5,8,5,Medium
126,P211,73,1,5,6,5,6,6,5,8,5,Medium
237,P311,73,1,5,6,5,6,6,5,8,5,Medium
348,P411,73,1,5,6,5,6,6,5,8,5,Medium
459,P511,73,1,5,6,5,6,6,5,8,5,Medium
570,P611,73,1,5,6,5,6,6,5,8,5,Medium
681,P711,73,1,5,6,5,6,6,5,8,5,Medium
792,P811,73,1,5,6,5,6,6,5,8,5,Medium
889,P9,73,1,5,6,5,6,6,5,8,5,Medium
903,P911,73,1,5,6,5,6,6,5,8,5,Medium

In [37]:
df.loc[(df["Alcohol use"] == 6) & (df["Balanced Diet"] == 6) & (df["Smoking"] == 8)]

#seems like we were unsuccesfull these patients were the only people coming from this kind of section

,Patient Id,Age,Gender,Air Pollution,Alcohol use,Dust Allergy,OccuPational Hazards,Genetic Risk,chronic Lung Disease,Balanced Diet,...,Fatigue,Weight Loss,Shortness of Breath,Wheezing,Swallowing Difficulty,Clubbing of Finger Nails,Frequent Cold,Dry Cough,Snoring,Level
15,P111,73,1,5,6,6,5,6,5,6,...,4,3,6,2,1,2,1,6,2,Medium
126,P211,73,1,5,6,6,5,6,5,6,...,4,3,6,2,1,2,1,6,2,Medium
237,P311,73,1,5,6,6,5,6,5,6,...,4,3,6,2,1,2,1,6,2,Medium
348,P411,73,1,5,6,6,5,6,5,6,...,4,3,6,2,1,2,1,6,2,Medium
459,P511,73,1,5,6,6,5,6,5,6,...,4,3,6,2,1,2,1,6,2,Medium
570,P611,73,1,5,6,6,5,6,5,6,...,4,3,6,2,1,2,1,6,2,Medium
681,P711,73,1,5,6,6,5,6,5,6,...,4,3,6,2,1,2,1,6,2,Medium
792,P811,73,1,5,6,6,5,6,5,6,...,4,3,6,2,1,2,1,6,2,Medium
889,P9,73,1,5,6,6,5,6,5,6,...,4,3,6,2,1,2,1,6,2,Medium
903,P911,73,1,5,6,6,5,6,5,6,...,4,3,6,2,1,2,1,6,2,Medium

In [119]:
df.loc[(df["Air Pollution"] <= 5) & (df["OccuPational Hazards"] <= 5) & (df["Genetic Risk"] <= 6) & (df["Passive Smoker"] <= 5) & (df["Level"] == "High"),["Patient Id","Age","Gender","Air Pollution","Alcohol use","OccuPational Hazards","Genetic Risk","Balanced Diet","Obesity","Smoking","Passive Smoker","Level"]]

# this means around 5% of the patients got cancer eventhough they have relatively better envirenement and low smokinga nd alcohol consumption
#they all have common obesity as 7
# we can futher ceck them if they were delayed to got the treatement while checking the intensity of the symptoms

,Patient Id,Age,Gender,Air Pollution,Alcohol use,OccuPational Hazards,Genetic Risk,Balanced Diet,Obesity,Smoking,Passive Smoker,Level
2,P100,35,1,4,5,5,5,6,7,2,3,High
5,P102,35,1,4,5,5,5,6,7,2,3,High
21,P117,53,2,4,5,5,5,6,7,2,3,High
57,P15,53,2,4,5,5,5,6,7,2,3,High
92,P181,35,2,4,5,5,5,6,7,2,3,High
99,P188,29,2,4,5,5,5,6,7,2,3,High
109,P197,25,2,4,5,5,5,6,7,2,3,High
116,P202,35,2,4,5,5,5,6,7,2,3,High
132,P217,53,2,4,5,5,5,6,7,2,3,High
203,P281,35,2,4,5,5,5,6,7,2,3,High
210,P288,29,2,4,5,5,5,6,7,2,3,High
220,P297,25,2,4,5,5,5,6,7,2,3,High
227,P302,35,1,4,5,5,5,6,7,2,3,High
243,P317,53,2,4,5,5,5,6,7,2,3,High
314,P381,35,2,4,5,5,5,6,7,2,3,High
321,P388,29,2,4,5,5,5,6,7,2,3,High
331,P397,25,2,4,5,5,5,6,7,2,3,High
338,P402,35,1,4,5,5,5,6,7,2,3,High
354,P417,53,2,4,5,5,5,6,7,2,3,High
425,P481,45,1,4,5,5,5,6,7,2,3,High
432,P488,39,1,4,5,5,5,6,7,2,3,High
442,P497,25,1,4,5,5,5,6,7,2,3,High
449,P502,35,1,4,5,5,5,6,7,2,3,High
465,P517,53,1,4,5,5,5,6,7,2,3,High
536,P581,35,2,4,5,5,5,6,7,2,3,High
543,P588,29,2,4,5,5,5,6,7,2,3,High
553,P597,25,2,4,5,5,5,6,7,2,3,High
560,P602,35,1,4,5,5,5,6,7,2,3,High
576,P617,53,2,4,5,5,5,6,7,2,3,High
647,P681,35,2,4,5,5,5,6,7,2,3,High
654,P688,29,2,4,5,5,5,6,7,2,3,High
664,P697,25,2,4,5,5,5,6,7,2,3,High
671,P702,35,1,4,5,5,5,6,7,2,3,High
687,P717,53,2,4,5,5,5,6,7,2,3,High
758,P781,35,2,4,5,5,5,6,7,2,3,High
765,P788,29,2,4,5,5,5,6,7,2,3,High
767,P79,35,2,4,5,5,5,6,7,2,3,High
775,P797,25,2,4,5,5,5,6,7,2,3,High
782,P802,35,1,4,5,5,5,6,7,2,3,High
798,P817,53,2,4,5,5,5,6,7,2,3,High
845,P86,29,2,4,5,5,5,6,7,2,3,High
869,P881,35,2,4,5,5,5,6,7,2,3,High
876,P888,29,2,4,5,5,5,6,7,2,3,High
886,P897,25,2,4,5,5,5,6,7,2,3,High
893,P902,35,2,4,5,5,5,6,7,2,3,High
909,P917,53,2,4,5,5,5,6,7,2,3,High
945,P95,25,2,4,5,5,5,6,7,2,3,High
980,P981,35,2,4,5,5,5,6,7,2,3,High
987,P988,29,2,4,5,5,5,6,7,2,3,High
997,P997,25,2,4,5,5,5,6,7,2,3,High

In [124]:

df.loc[(df["Level"] == "High"),["Patient Id","Age","Gender","Balanced Diet","Obesity","Smoking","Passive Smoker","Fatigue","Dust Allergy","chronic Lung Disease","Chest Pain","Coughing of Blood","Level",]]

#as we can see the the coughing of blood is a major symptom of cancer, it worsens as the cancer stage grows to dangerous levels , as we can see the patients with low level of blodd coughing had a low level of cancer while as the level incerase 
# the level of cancer incerases since these patient had great enviroemnt conditiin and got the hgih level of canvcer largely due to the late treatement they got,

,Patient Id,Age,Gender,Balanced Diet,Obesity,Smoking,Passive Smoker,Fatigue,Dust Allergy,chronic Lung Disease,Chest Pain,Coughing of Blood,Level
2,P100,35,1,6,7,2,3,8,6,4,4,8,High
3,P1000,37,1,7,7,7,7,4,7,7,7,8,High
4,P101,46,1,7,7,8,7,3,7,6,7,9,High
5,P102,35,1,6,7,2,3,8,6,4,4,8,High
10,P107,44,1,7,7,7,8,5,7,6,7,7,High
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,P995,44,1,7,7,7,8,5,7,6,7,7,High
996,P996,37,2,7,7,7,8,9,7,6,7,7,High
997,P997,25,2,6,7,2,3,8,6,4,4,8,High
998,P998,18,2,7,7,8,7,3,7,6,7,9,High
999,P999,47,1,6,7,2,3,8,6,4,4,8,High

In [52]:
ev_mid = df.loc[(df["Air Pollution"] <= 5) & (df["OccuPational Hazards"] <= 5) & (df["Genetic Risk"] <= 6) & (df["Passive Smoker"] <= 5) & (df["Level"] == "Medium"),["Patient Id","Age","Gender","Air Pollution","Alcohol use","OccuPational Hazards","Genetic Risk","Balanced Diet","Obesity","Smoking","Passive Smoker","Level"]]
ev_mid
# here about 20% of the patients who got the cancer at medium level were living in a best environement with very low consmptino of alchohol and smoking , while maintainig ahelay life with less obesity and balanced diet

,Patient Id,Age,Gender,Air Pollution,Alcohol use,OccuPational Hazards,Genetic Risk,Balanced Diet,Obesity,Smoking,Passive Smoker,Level
1,P10,17,1,3,1,3,4,2,2,2,4,Medium
9,P106,46,1,2,3,2,4,3,3,2,3,Medium
15,P111,73,1,5,6,5,6,6,5,8,5,Medium
16,P112,17,1,3,1,3,4,2,2,2,4,Medium
26,P121,38,2,2,1,3,2,2,4,1,4,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...
971,P973,36,2,2,1,3,2,2,4,1,4,Medium
972,P974,31,2,3,2,2,3,3,3,2,2,Medium
973,P975,38,2,1,2,4,2,3,3,3,2,Medium
983,P984,26,1,3,2,2,3,3,3,2,2,Medium
984,P985,37,1,1,2,4,2,3,3,3,2,Medium

In [62]:
ev_low = df.loc[(df["Air Pollution"] <= 5) & (df["OccuPational Hazards"] <= 5) & (df["Genetic Risk"] <= 5) & (df["Passive Smoker"] <= 5) & (df["Level"] == "Low"),["Patient Id","Age","Gender","Air Pollution","Alcohol use","OccuPational Hazards","Genetic Risk","Balanced Diet","Obesity","Smoking","Passive Smoker","Level"]]
ev_low.describe()

#mailny 25 % of the people lead a helthy life with low Genetic risk has got a very low cancer level

,Age,Gender,Air Pollution,Alcohol use,OccuPational Hazards,Genetic Risk,Balanced Diet,Obesity,Smoking,Passive Smoker
count,263.000000,263.000000,263.000000,263.00000,263.000000,263.000000,263.000000,263.000000,263.000000,263.000000
mean,35.133080,1.547529,2.577947,2.00000,2.695817,2.311787,2.695817,2.395437,2.684411,2.425856
std,12.671472,0.498685,0.924955,0.92876,1.029462,0.820616,1.101119,1.078723,1.585726,1.245303
min,17.000000,1.000000,1.000000,1.00000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
25%,25.000000,1.000000,2.000000,1.00000,2.000000,2.000000,2.000000,1.000000,2.000000,2.000000
50%,33.000000,2.000000,3.000000,2.00000,3.000000,2.000000,3.000000,2.000000,2.000000,2.000000
75%,42.500000,2.000000,3.000000,3.00000,4.000000,3.000000,3.000000,3.000000,3.000000,4.000000
max,62.000000,2.000000,5.000000,4.00000,4.000000,4.000000,5.000000,4.000000,7.000000,5.000000

In [63]:
df.loc[(df["Smoking"]>3) & (df["Alcohol use"] > 5) & (df["Air Pollution"] <= 5) & (df["OccuPational Hazards"] <= 5) & (df["Genetic Risk"] <= 5) & (df["Passive Smoker"] <= 5) & (df["Level"] == "Low"),["Patient Id","Age","Gender","Air Pollution","Alcohol use","OccuPational Hazards","Genetic Risk","Balanced Diet","Obesity","Smoking","Passive Smoker","Level"]]

Empty DataFrame
Columns: [Patient Id, Age, Gender, Air Pollution, Alcohol use, OccuPational Hazards, Genetic Risk, Balanced Diet, Obesity, Smoking, Passive Smoker, Level]
Index: []

as a result we can say that the enviornement plays a major role in cancer the better enviornement and better lifestyle leads to a low 
level of cancer 
a interesting fact is these people tend to have less tendecny to alchohol and smoking
but as we go to severe levels the patients living environement and habits becomes unhealthy which results us in a severe level of cancer

as a result the enviornement, occupation hazards and etc will directly causes the unhelathy habitats which inturn leads to severe levels of cancer

In [54]:
ev_mid.loc[(ev_mid["Age"] >= 20) & (ev_mid["Age"] <= 50)]

#about majority of the people were middle aged 
#now lets look for the patients with healty diet and helthy living condition

,Patient Id,Age,Gender,Air Pollution,Alcohol use,OccuPational Hazards,Genetic Risk,Balanced Diet,Obesity,Smoking,Passive Smoker,Level
9,P106,46,1,2,3,2,4,3,3,2,3,Medium
26,P121,38,2,2,1,3,2,2,4,1,4,Medium
29,P124,28,2,1,6,5,3,6,2,3,3,Medium
63,P155,45,2,1,2,4,2,3,3,3,2,Medium
65,P157,44,1,2,1,3,2,2,4,1,4,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...
971,P973,36,2,2,1,3,2,2,4,1,4,Medium
972,P974,31,2,3,2,2,3,3,3,2,2,Medium
973,P975,38,2,1,2,4,2,3,3,3,2,Medium
983,P984,26,1,3,2,2,3,3,3,2,2,Medium
984,P985,37,1,1,2,4,2,3,3,3,2,Medium

### Symptoms and the level of Cancer

In [102]:
symptoms = ["Dust Allergy","chronic Lung Disease","Chest Pain","Coughing of Blood","Fatigue","Weight Loss","Shortness of Breath","Wheezing","Swallowing Difficulty","Clubbing of Finger Nails","Frequent Cold","Dry Cough","Level"]

In [70]:
sym = df.loc[(df["Dust Allergy"] > 5) & (df["chronic Lung Disease"]>5) & (df["Chest Pain"]>5) & (df["Coughing of Blood"]>5) & (df["Fatigue"]>5) & (df["Weight Loss"]>5) & (df["Shortness of Breath"]>5) & (df["Wheezing"]>5) & (df["Swallowing Difficulty"]>5) & (df["Clubbing of Finger Nails"]>5) & (df["Frequent Cold"]>5) & (df["Dry Cough"]>5), ["Dust Allergy","chronic Lung Disease","Chest Pain","Coughing of Blood","Fatigue","Weight Loss","Shortness of Breath","Wheezing","Swallowing Difficulty","Clubbing of Finger Nails","Frequent Cold","Dry Cough"]]
sym

Empty DataFrame
Columns: [Dust Allergy, chronic Lung Disease, Chest Pain, Coughing of Blood, Fatigue, Weight Loss, Shortness of Breath, Wheezing, Swallowing Difficulty, Clubbing of Finger Nails, Frequent Cold, Dry Cough]
Index: []

In [109]:
sym = temp.loc[:,["Dust Allergy","chronic Lung Disease","Chest Pain","Coughing of Blood","Fatigue","Weight Loss","Shortness of Breath","Wheezing","Swallowing Difficulty","Clubbing of Finger Nails","Frequent Cold","Dry Cough","Level"]]
sym.corr()

#from this we know that the facor like Dust Allergy,Chronic Lung Disease,chest pain,Coghing of blood *mainly*, and fatigue are highly related with the level of the cancer we have as a result consider these symptoms for the cancer

,Dust Allergy,chronic Lung Disease,Chest Pain,Coughing of Blood,Fatigue,Weight Loss,Shortness of Breath,Wheezing,Swallowing Difficulty,Clubbing of Finger Nails,Frequent Cold,Dry Cough,Level
Dust Allergy,1.000000,0.619556,0.639983,0.625291,0.332472,0.321756,0.518682,0.304850,0.031141,0.345714,0.219389,0.300195,0.713839
chronic Lung Disease,0.619556,1.000000,0.782646,0.602987,0.247697,0.104080,0.182426,0.057214,0.007279,0.298023,0.028759,0.114161,0.609971
Chest Pain,0.639983,0.782646,1.000000,0.712158,0.251135,-0.001092,0.237045,0.107211,0.071784,0.081386,0.042937,0.142180,0.645461
Coughing of Blood,0.625291,0.602987,0.712158,1.000000,0.481540,0.105857,0.318777,-0.085698,0.086289,-0.066443,0.244235,0.147659,0.782092
Fatigue,0.332472,0.247697,0.251135,0.481540,1.000000,0.469517,0.398625,0.174477,0.149562,0.040694,0.407915,0.271167,0.625114
Weight Loss,0.321756,0.104080,-0.001092,0.105857,0.469517,1.000000,0.574497,0.331179,0.053384,0.376484,0.160348,0.188598,0.352738
Shortness of Breath,0.518682,0.182426,0.237045,0.318777,0.398625,0.574497,1.000000,0.207564,-0.200477,0.474275,0.351489,0.493331,0.497024
Wheezing,0.304850,0.057214,0.107211,-0.085698,0.174477,0.331179,0.207564,1.000000,0.393487,0.338271,0.098855,0.054388,0.242794
Swallowing Difficulty,0.031141,0.007279,0.071784,0.086289,0.149562,0.053384,-0.200477,0.393487,1.000000,-0.119741,0.132363,-0.055428,0.249142
Clubbing of Finger Nails,0.345714,0.298023,0.081386,-0.066443,0.040694,0.376484,0.474275,0.338271,-0.119741,1.000000,0.242529,0.307271,0.280063
Frequent Cold,0.219389,0.028759,0.042937,0.244235,0.407915,0.160348,0.351489,0.098855,0.132363,0.242529,1.000000,0.515918,0.444017
Dry Cough,0.300195,0.114161,0.142180,0.147659,0.271167,0.188598,0.493331,0.054388,-0.055428,0.307271,0.515918,1.000000,0.373968
Level,0.713839,0.609971,0.645461,0.782092,0.625114,0.352738,0.497024,0.242794,0.249142,0.280063,0.444017,0.373968,1.000000

In [98]:
temp

,Patient Id,Age,Gender,Air Pollution,Alcohol use,Dust Allergy,OccuPational Hazards,Genetic Risk,chronic Lung Disease,Balanced Diet,...,Fatigue,Weight Loss,Shortness of Breath,Wheezing,Swallowing Difficulty,Clubbing of Finger Nails,Frequent Cold,Dry Cough,Snoring,Level
0,P1,33,1,2,4,5,4,3,2,2,...,3,4,2,2,3,1,2,3,4,1
1,P10,17,1,3,1,5,3,4,2,2,...,1,3,7,8,6,2,1,7,2,2
2,P100,35,1,4,5,6,5,5,4,6,...,8,7,9,2,1,4,6,7,2,3
3,P1000,37,1,7,7,7,7,6,7,7,...,4,2,3,1,4,5,6,7,5,3
4,P101,46,1,6,8,7,7,7,6,7,...,3,2,4,1,4,2,4,2,3,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,P995,44,1,6,7,7,7,7,6,7,...,5,3,2,7,8,2,4,5,3,3
996,P996,37,2,6,8,7,7,7,6,7,...,9,6,5,7,2,4,3,1,4,3
997,P997,25,2,4,5,6,5,5,4,6,...,8,7,9,2,1,4,6,7,2,3
998,P998,18,2,6,8,7,7,7,6,7,...,3,2,4,1,4,2,4,2,3,3
999,P999,47,1,6,5,6,5,5,4,6,...,8,7,9,2,1,4,6,7,2,3

In [85]:
temp = df

In [93]:
temp

,Patient Id,Age,Gender,Air Pollution,Alcohol use,Dust Allergy,OccuPational Hazards,Genetic Risk,chronic Lung Disease,Balanced Diet,...,Fatigue,Weight Loss,Shortness of Breath,Wheezing,Swallowing Difficulty,Clubbing of Finger Nails,Frequent Cold,Dry Cough,Snoring,Level
0,P1,33,1,2,4,5,4,3,2,2,...,3,4,2,2,3,1,2,3,4,1
1,P10,17,1,3,1,5,3,4,2,2,...,1,3,7,8,6,2,1,7,2,2
2,P100,35,1,4,5,6,5,5,4,6,...,8,7,9,2,1,4,6,7,2,3
3,P1000,37,1,7,7,7,7,6,7,7,...,4,2,3,1,4,5,6,7,5,3
4,P101,46,1,6,8,7,7,7,6,7,...,3,2,4,1,4,2,4,2,3,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,P995,44,1,6,7,7,7,7,6,7,...,5,3,2,7,8,2,4,5,3,3
996,P996,37,2,6,8,7,7,7,6,7,...,9,6,5,7,2,4,3,1,4,3
997,P997,25,2,4,5,6,5,5,4,6,...,8,7,9,2,1,4,6,7,2,3
998,P998,18,2,6,8,7,7,7,6,7,...,3,2,4,1,4,2,4,2,3,3
999,P999,47,1,6,5,6,5,5,4,6,...,8,7,9,2,1,4,6,7,2,3

In [127]:
df.loc[(df["Level"] == "Low") & (df["Balanced Diet"] > 7 ) & (df["Air Pollution"] < 4) & (df["OccuPational Hazards"] < 4)]

#as we can see the people with healthy background got no cancer according to our dataset

Empty DataFrame
Columns: [Patient Id, Age, Gender, Air Pollution, Alcohol use, Dust Allergy, OccuPational Hazards, Genetic Risk, chronic Lung Disease, Balanced Diet, Obesity, Smoking, Passive Smoker, Chest Pain, Coughing of Blood, Fatigue, Weight Loss, Shortness of Breath, Wheezing, Swallowing Difficulty, Clubbing of Finger Nails, Frequent Cold, Dry Cough, Snoring, Level]
Index: []

[0 rows x 25 columns]

## Conclusion

Based on the analysis we classified the dataset into three with two type of patients and symptoms

after analysing the first category of user considering their unhealthy habits are the reason for cancer , we found out the trend of 
unhealthy habits become dependant on the Enviornment they are living , such as their friends , office enviornement, Air polltion etc
by focusing on these enviorenments we figured the users got cancer was even after they are from a healthy enviornement was due to their genes
their own unhealthy habits

and some of the people who got high level of cancer which was unlkely for them to have ,further checking their symproms found it was dues to
their late treatement

further more the majority of the patients who got high level cancer were middle aged people from a range if Age 20 to 50,
and the old people with age above 50 got middle level caner

while the young womans of age 18 got cancer of high level , which was caused due to their unhealthy enviornement