In [13]:
import pandas as pd

df = pd.read_csv("./dataset/course.csv")

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3678 entries, 0 to 3677
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   course_id            3678 non-null   int64
 1   course_title         3678 non-null   object
 2   url                  3678 non-null   object
 3   is_paid              3678 non-null   bool
 4   price                3678 non-null   int64
 5   num_subscribers      3678 non-null   int64
 6   num_reviews          3678 non-null   int64
 7   num_lectures         3678 non-null   int64
 8   level                3678 non-null   object
 9   content_duration     3678 non-null   float64
 10  published_timestamp  3678 non-null   object
 11  subject              3678 non-null   object
dtypes: bool(1), float64(1), int64(5), object(5)
memory usage: 319.8+ KB

In [39]:
df.head()

,course_id,course_title,url,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
0,1070968,Ultimate Investment Banking Course,https://www.udemy.com/ultimate-investment-bank...,True,200,2147,23,51,All Levels,0 days 00:00:00.000000001,2017-01-18 20:58:58+00:00,Business Finance
1,1113822,Complete GST Course & Certification - Grow You...,https://www.udemy.com/goods-and-services-tax/,True,75,2792,923,274,All Levels,0 days 00:00:00.000000039,2017-03-09 16:34:20+00:00,Business Finance
2,1006314,Financial Modeling for Business Analysts and C...,https://www.udemy.com/financial-modeling-for-b...,True,45,2174,74,51,Intermediate Level,0 days 00:00:00.000000002,2016-12-19 19:26:30+00:00,Business Finance
3,1210588,Beginner to Pro - Financial Analysis in Excel ...,https://www.udemy.com/complete-excel-finance-c...,True,95,2451,11,36,All Levels,0 days 00:00:00.000000003,2017-05-30 20:07:24+00:00,Business Finance
4,1011058,How To Maximize Your Profits Trading Options,https://www.udemy.com/how-to-maximize-your-pro...,True,200,1276,45,26,Intermediate Level,0 days 00:00:00.000000002,2016-12-13 14:57:18+00:00,Business Finance

In [36]:
df[df.duplicated()]

Empty DataFrame
Columns: [course_id, course_title, url, is_paid, price, num_subscribers, num_reviews, num_lectures, level, content_duration, published_timestamp, subject]
Index: []

In [35]:
df.drop_duplicates(inplace = True)

In [21]:
df["course_id"].nunique()

3672

In [29]:
df["published_timestamp"] = pd.to_datetime(df["published_timestamp"],format = "mixed")
df.dtypes

course_id                            int64
course_title                        object
url                                 object
is_paid                               bool
price                                int64
num_subscribers                      int64
num_reviews                          int64
num_lectures                         int64
level                               object
content_duration                   float64
published_timestamp    datetime64[ns, UTC]
subject                             object
dtype: object

In [38]:
df["content_duration"] = df["content_duration"].astype("timedelta64[ns]")
df.dtypes

course_id                            int64
course_title                        object
url                                 object
is_paid                               bool
price                                int64
num_subscribers                      int64
num_reviews                          int64
num_lectures                         int64
level                               object
content_duration           timedelta64[ns]
published_timestamp    datetime64[ns, UTC]
subject                             object
dtype: object

In [42]:
df.shape

(3672, 12)

In [48]:
df["content_duration"].min()

Timedelta('0 days 00:00:00')

In [51]:
df.loc[(df["content_duration"]<="0 days 00:00:00"),["course_id","course_title","published_timestamp"]]

,course_id,course_title,published_timestamp
19,58977,Financial Statements Made Easy,2013-06-09 00:21:26+00:00
91,1217064,How To Invest With Tiny Capital In Stocks ?,2017-05-23 16:07:09+00:00
95,1148774,Options Trading 101: The Basics,2017-03-23 22:19:57+00:00
116,1191504,How to create a routine Trading,2017-05-01 18:50:43+00:00
117,585752,"Forex Trading Secrets |MT4 Robot (EA) inside, ...",2015-08-24 22:16:54+00:00
...,...,...,...
3649,1018530,Cakephp:Creating a CRUD application,2016-11-22 17:55:42+00:00
3655,833182,JQuery DOM and Ajax Concept Explained for Begi...,2016-04-27 15:26:57+00:00
3666,968292,XPATH :basics for beginners,2016-09-27 15:20:47+00:00
3667,523216,The Fastest Way to Create a Website Using Godaddy,2015-11-09 20:44:25+00:00
3668,270976,A how to guide in HTML,2014-08-10 20:19:10+00:00

In [58]:
df.loc[(df["price"]>0) & (df["is_paid"] == False),["course_id"]]

Empty DataFrame
Columns: [course_id]
Index: []

In [61]:
df.loc[(df["price"].max() == df["price"])]

,course_id,course_title,url,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
0,1070968,Ultimate Investment Banking Course,https://www.udemy.com/ultimate-investment-bank...,True,200,2147,23,51,All Levels,0 days 00:00:00.000000001,2017-01-18 20:58:58+00:00,Business Finance
4,1011058,How To Maximize Your Profits Trading Options,https://www.udemy.com/how-to-maximize-your-pro...,True,200,1276,45,26,Intermediate Level,0 days 00:00:00.000000002,2016-12-13 14:57:18+00:00,Business Finance
9,1167710,The Only Investment Strategy You Need For Your...,https://www.udemy.com/the-only-investment-stra...,True,200,827,14,15,All Levels,0 days 00:00:00.000000001,2017-04-18 18:13:32+00:00,Business Finance
10,592338,Forex Trading Secrets of the Pros With Amazon'...,https://www.udemy.com/trading-with-amazons-aws...,True,200,4284,93,76,All Levels,0 days 00:00:00.000000005,2015-09-11 16:47:02+00:00,Business Finance
11,975046,Trading Options With Money Flow,https://www.udemy.com/trading-options-using-mo...,True,200,1380,42,17,All Levels,0 days 00:00:00.000000001,2016-10-18 22:52:31+00:00,Business Finance
...,...,...,...,...,...,...,...,...,...,...,...,...
3592,976854,Spring 4 Mastercourse: Covers Annotation & XML...,https://www.udemy.com/java-spring-framework/,True,200,1353,53,320,Intermediate Level,0 days 00:00:00.000000023,2016-11-01 22:08:04+00:00,Web Development
3620,1227578,Learning Path: The Road to Elasticsearch,https://www.udemy.com/learning-path-the-road-t...,True,200,50,5,60,Beginner Level,0 days 00:00:00.000000005,2017-05-29 17:56:24+00:00,Web Development
3642,709324,Learn Web Development by Creating a Social Net...,https://www.udemy.com/meteor-tutorial/,True,200,442,48,80,Beginner Level,0 days 00:00:00.000000006,2015-12-30 16:53:44+00:00,Web Development
3652,919354,Learn Bootstrap 4 The Most Popular HTML5 CSS3 ...,https://www.udemy.com/learn-bootstrap-4-the-mo...,True,200,279,37,119,All Levels,0 days 00:00:00.000000010,2017-04-25 00:57:35+00:00,Web Development
3654,949134,The Extreme Web Development Course - For Begin...,https://www.udemy.com/the-extreme-web-developm...,True,200,1420,62,152,All Levels,0 days 00:00:00.000000005,2016-09-04 20:51:08+00:00,Web Development

In [68]:
df.groupby("level")["price"].sum()

level
All Levels            140700
Beginner Level         70675
Expert Level            5285
Intermediate Level     26070
Name: price, dtype: int64